### ISSUE TITLE
Nullable columns do not have DEFAULT NULL in the generated API

### ISSUE THREAD

**Issue by softinn72** [OraMUC/table-api-generator#12]
Hi,
while using your generator (latest release 0.4.1) I noticed that nullable table columns do not get a DEFAULT NULL in the related parameter of the generated create_row API, so I am forced to declare all the parameters when calling the API instead of leaving out the nullable ones. I think this is not very user friendly, but maybe there is some other reason for this choice. Do you think you can change this behaviour?

Anyway I have modified the package locally to add the DEFAULT NULL string when a nullable column is detected. Are you interested to my small contribution?

Thanks,
Paolo

**Comment by aborngra** [comment]
Hi Paolo,

this is a good point and we already discussed a lot about that. First of all, you are absolutely right, we are only talking about the **create_row** methods because within the other ones -  it could be dangerous having defaults. 
In addition to your suggested nullable column defaults topic, we thought **generally about taking defaults** if possible. "If possible" means something like that:

- if column default value exists, take it as default param
- if no column default value exists and if the column is nullable take null as default param
- else don't take a default param

Hope it makes also sense for you.

The question if a column is nullable is unfortunately not 100% clear in my eyes. Sure you can query the dictionary and check the nullable attribute. In the following case:
```
CREATE TABLE abo_test
(
   col1 NUMBER CONSTRAINT abo_test_nn1 NOT NULL
 , col2 NUMBER
 , CONSTRAINT abo_test_nn2 CHECK(col2 IS NOT NULL)
);
```
both columns have not null checks. But for col2 the nullable attribute of the dictionary would say 'Y' even though there is a not null check constraint. I only wanted to point out this little inaccuracy and say - we have to parse the search_condition column for check constraints to find out if a column is "really nullable". 

And this is exactly the reason why we shifted this default topic until äääh ... now ;-) but I understand your point, perhaps now we have the need to implement it... yes I think we can change this behaviour.

Thanks Paolo for your idea
André

**Comment by ogobrecht** [comment]
Hi Paolo,

When we started to implement our table API generator one of the ideas was that business logic built on top of the API should become invalid, when the underlaying data model changes. With this in mind we decided not to have defaults on the `create_row` methods, because when the API changes (e.g. a new column is added), then all business logic using the `create_row` methods will become invalid and you can be sure that you don't forget something.

Since then we have also implemented row based methods and in some scenarios those are very handy. The bad thing with the row based methods is, that we now could not be sure that all the business logic is up to date after data model changes - the row based methods are normally still valid. So the reasons not to have defaults are not so hard anymore.

May be you had a look at the other issues - there are some disussions about defaults and the upcoming version will have support for defaults. But I think your feedback is still very helpful to rethink the current development implementation of the defaults handling - see also the branch `0.5` the `README.md`.

In the meantime you can mimic column defaults regarding null values with the latest release like so:

```sql
DECLARE
  v_row employees%ROWTYPE;
BEGIN
  v_row.last_name := 'Bean';
  v_row.email     := 'Mr.Bean@dummydomain.com';
  v_row.hire_date := DATE '1970-01-01';
  v_row.job_id    := 1;
  employees_api.create_row(p_row => v_row);
END;
```

Hope this helps and best regards  
Ottmar

**Comment by ogobrecht** [comment]
uuups, sorry, during my writing André already answered your question - the good thing is: Hopefully you get the full picture :-)

Best regards
Ottmar

**Comment by softinn72** [comment]
Thank you both for the explanations! I just learned the hard way why having defaults on nullable columns may become problematic, if not handled correctly... :)

**Comment by softinn72** [comment]
Thank you both for the explanations! I just learned the hard way why having defaults on nullable columns may become problematic, if not handled correctly... :)

**Comment by ogobrecht** [comment]
Hi Paolo,

the new version 0.5.0 is out. It supports default values for the create methods. Therefore I close now this issue. Please let us know, if you have any further question.

Best regards
Ottmar

**Comment by softinn72** [comment]
Thanks Ottmar,
thanks for implementing it, I will try to test the new version as time permits. 
In the meantime I wish you a merry Christmas!

**Comment by ogobrecht** [comment]
Thank you Paolo, also merry Christmas and a happy new year to you!
