### ISSUE TITLE
Add returning into all non-blob-columns

### ISSUE THREAD

**Issue by MaikMichel** [OraMUC/table-api-generator#16]
Hi, instead of returning just the primary-key you can return all non-blob-columns into record. And that when insert AND update is used. Why? Because that would show the results of all triggers fired on that row. In my case that is the filling of audit-columns.

**Comment by ogobrecht** [comment]
Hi Maik,

which version you are using?

In our current dev branch 0.5 there is a new parameter `return_row_instead_of_pk`. If this parameter is set to true the resulting API returns the whole row.

Unfortunately we have not finished the development of the new version. But you can check out the 0.5 branch and test it - should be stable enough.

Please let us know, if this is what you need. We do not distinguish between blob or non blob. You can have the primary key or the whole record.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Maik,

the new version 0.5.0 is out. You can set [an option to return the row instead of the primary key](https://github.com/OraMUC/table-api-generator/blob/master/docs/parameters.md#p_return_row_instead_of_pk). Therefore I close this issue.

If you have any further questions please let us know.

Best regards
Ottmar
