### ISSUE TITLE
Toggle not to use NotNull-Constraints

### ISSUE THREAD

**Issue by MaikMichel** [OraMUC/table-api-generator#17]
Hi, the api takes care of NotNull-Columns. But there  exists some trigger-logik that will places the values to these columns. It would be fine to toggle this behaviour.

**Comment by ogobrecht** [comment]
Hi Maik,

please provide the version you are using and some code example what the generator currently does and specify in more detail what you want to have in which methods.

Thank you and best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Maik,

any news on this issue? Can you provide more details as requested by me back in 2018? Or is this obsolete and we can close the issue? The new version 0.6.0 of the generator is out as I already mentioned in another issue.

Best regards
Ottmar

**Comment by MaikMichel** [comment]
Hi Ottmar,

I'm sorry that I haven't reported on this for so long....
So the following example:
table xyz
...
column_a,
column_b not null,
column_c,

trigger-logic on insert or update ...
...
:new.column_b := calc_business_logic(...) or find_reference_column_based_on_some_logic(...);
...

In this case, it would be nice to exclude column_b from the required list of columns for a transaction.

Thanks for your patience,
Maik

**Comment by ogobrecht** [comment]
Hi Maik,

thank you for the feedback. Since version 0.5.0 of the generator you can explicitly exclude columns for this type of use cases - please have a look at the [parameter docs for `p_exclude_column_list`](https://github.com/OraMUC/table-api-generator/blob/master/docs/parameters.md#p_exclude_column_list-since-v050). 

If this is not the solution for your use case then please let us know and reopen the issue.

Best regards
Ottmar
