### ISSUE TITLE
Primary key not returned on create_row when XMLTYPE column is present

### ISSUE THREAD

**Issue by softinn72** [OraMUC/table-api-generator#29]
Hi Ottmar,
it seems I found a bug in the generated API package where in a very specific case the create_row API function is not returning the PK after successfully creating the record. The issue is present in version 0.5.0, but it worked fine in previous versions. Our database is version 12c (12.2.0.1.0).

Here is a quick test case:
```sql
CREATE TABLE test
  (
    table_id NUMBER NOT NULL CONSTRAINT table_id_pk PRIMARY KEY
  , xml_template XMLTYPE
  );

CREATE SEQUENCE TEST_SEQ INCREMENT BY 1 START WITH 1;

BEGIN
  om_tapigen.compile_api(p_table_name => 'TEST', p_sequence_name => 'TEST_SEQ');
END;
/

SET SERVEROUTPUT ON SIZE UNLIMITED
DECLARE
  l_table_id TEST.table_id%TYPE;
BEGIN
  l_table_id := test_api.create_row(p_xml_template => XMLTYPE('<TEST/>'));
  -- verify that the function did not return the PK 
  dbms_output.put_line('l_table_id='||TO_CHAR(l_table_id));
END;
/
-- verify that the record was created successfully
SELECT * FROM test;
```

By looking at the generated code, it's easy to spot why the PK will not be correctly returned, since the sequence value is not considered at all:
```sql
  FUNCTION create_row (
    p_table_id     IN "TEST"."TABLE_ID"%TYPE DEFAULT NULL /*PK*/,
    p_xml_template IN "TEST"."XML_TEMPLATE"%TYPE )
  RETURN "TEST"."TABLE_ID"%TYPE IS
    v_return "TEST"."TABLE_ID"%TYPE;
  BEGIN
    INSERT INTO "TEST" (
      "TABLE_ID" /*PK*/,
      "XML_TEMPLATE" )
    VALUES (
      COALESCE( p_table_id, "TEST_SEQ".nextval ),
      p_xml_template );
    -- returning clause does not support XMLTYPE,so we do here an extra fetch
    v_return := read_row ( p_table_id => p_table_id )."TABLE_ID";
    RETURN v_return;
  END create_row;
```
Additionally I wonder why the returning clause is not used in this case, as the following amended code works fine in database 12c:
```sql
    INSERT INTO "TEST" (
      "TABLE_ID" /*PK*/,
      "XML_TEMPLATE" )
    VALUES (
      COALESCE( p_table_id, "TEST_SEQ".nextval ),
      p_xml_template )
      RETURN "TABLE_ID"
      INTO v_return;
```

**Comment by ogobrecht** [comment]
Hi Paolo,

confirmed. This is a Bug. We introduced in 0.5.0 the possibility to return the whole row instead of the primary key (parameter p_return_row_instead_of_pk ).

The problem is that returning all table columns into a row type variable is not working when you have a xmltype column in your table. Here two example blocks for your test table - the first one will run:

```sql
set serveroutput on size unlimited
declare
  v_row test%rowtype;
begin
  insert into test (
    table_id /*PK*/,
    xml_template
  ) values (
    test_seq.nextval,
    xmltype('<TEST/>')
  ) returning table_id into v_row.table_id;
  dbms_output.put_line('table_id=' || to_char(v_row.table_id));
end;
/
```
As soon as you include the xmltype column you will get an error (ORA-22816: unsupported feature with RETURNING clause):

```sql
set serveroutput on size unlimited
declare
  v_row test%rowtype;
begin
  insert into test (
    table_id /*PK*/,
    xml_template
  ) values (
    test_seq.nextval,
    xmltype('<TEST/>')
  ) returning table_id, xml_template into v_row;
  dbms_output.put_line('table_id=' || to_char(v_row.table_id));
end;
/
```

This was the reason to decide to do the extra fetch when an xml column is present. This should only be the case when also the parameter p_return_row_instead_of_pk is set - but we forgot this condition in the code.

I will fix this on the weekend and provide a corrected version. 

By the way, we are working currently on a new version which will introduce methods for bulk processing. Are you interested in this? If so, you are welcome as an early adopter for tests ;-)

You will hear from me the next days, best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Paolo,

the bugfix [release 0.5.1 is available](https://github.com/OraMUC/table-api-generator/releases). Thank you for reporting the issue.

Best regards
Ottmar

**Comment by softinn72** [comment]
Hi Ottmar,
thanks a lot for the quick fix and the explanation!

Indeed I'd be very interested in the bulk processing functionality of the new version and I hope to find some time to test the development version.

I also have a new enhancement request, but I'll open a new ticket for it.

Thanks again,
Paolo

**Comment by ogobrecht** [comment]
Hi Paolo,

some hints for the new version:

- We check in currently every running version in the branch named "development".
- The docs for using the bulk methods needs to be aligned.

There are breaking changes:

To have similar behaviour between the bulk and the standard methods we skipped the checking for changes - that means all updates are passed thru the table instead of checked, if any changes occured to the record to avoid unnecessary changes.

We skipped also the generic change log. This was a problem before when multi column primary keys exist and is now a bigger problem with the bulk methods. If you need this feature we recommend to use the flashback data archive and not a trigger based solution because this is slowing down your overall data model performance. Hopefully you are not used the generic change log in the past -otherwise you have some amount of work to migrate to an other solution - sorry for that.

We introduced support for audit columns. That means the table API can do this for you instead of a trigger based solution. You should hide your data model in an extra schema and give only execute rights to the APIs to avoid manipulation of the audit columns. This is known as the SmartDB od PinkDB paradigm - see also this [interesting post by Philip Salvisberg](https://www.salvis.com/blog/2018/07/18/the-pink-database-paradigm-pinkdb/).

Let me know, if you need more informations or if you have any questions.

Best regards
Ottmar
